name: btc_for_all
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.6

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  window_manager: ^0.4.2
  url_launcher: ^6.3.0
  fl_chart: ^0.69.0
  html: ^0.15.0
  intl: ^0.19.0
  archive: ^3.1.3
  dio: ^5.0.0
  path_provider: ^2.0.10
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/38.png
    - assets/images/pix.jpg

  uses-material-design: true
